# Generated by Django 4.2.9 on 2026-04-05 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entites', '0001_initial'),
        ('registres', '0001_initial'),
        ('parametrage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_dmd', models.CharField(max_length=30, unique=True, verbose_name='N° demande')),
                ('type_entite', models.CharField(blank=True, choices=[('PH', 'PH'), ('PM', 'PM'), ('SC', 'SC')], max_length=5)),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('SAISIE', 'Saisie'), ('SOUMISE', 'Soumise'), ('EN_TRAITEMENT', 'En traitement'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée'), ('ANNULEE', 'Annulée')], db_index=True, default='SAISIE', max_length=20)),
                ('motif_rejet', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('canal', models.CharField(choices=[('GUICHET', 'Guichet'), ('EN_LIGNE', 'En ligne')], default='GUICHET', max_length=20)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference_paiement', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_creees', to=settings.AUTH_USER_MODEL)),
                ('ph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entites.personnephysique')),
                ('pm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entites.personnemorale')),
                ('ra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='registres.registreanalytique')),
                ('sc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entites.succursale')),
                ('type_demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametrage.typedemande')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande',
                'verbose_name_plural': 'Demandes',
                'db_table': 'demandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=200)),
                ('present', models.BooleanField(default=False)),
                ('conforme', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='demandes.demande')),
                ('type_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametrage.typedocument')),
            ],
            options={
                'verbose_name': 'Ligne de demande',
                'verbose_name_plural': 'Lignes de demande',
                'db_table': 'lignes_demande',
            },
        ),
    ]
