# Generated by Django 4.2.11 on 2026-04-22 01:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('type_certificat', models.CharField(choices=[('inscription', "Certificat d'inscription (art. 78, 86)"), ('modification', 'Certificat de modification (art. 88-90)'), ('renouvellement', 'Certificat de renouvellement (art. 91)'), ('radiation', 'Certificat de radiation (art. 92)'), ('recherche', 'Certificat de recherche (art. 97)')], max_length=32, verbose_name='Type de certificat')),
                ('langue_generation', models.CharField(choices=[('fr', 'Français'), ('ar', 'Arabe'), ('fr-ar', 'Bilingue')], default='fr-ar', max_length=8, verbose_name='Langue de génération')),
                ('probant', models.BooleanField(default=False, help_text="Vaut ``True`` UNIQUEMENT si les conditions de scellement, d'horodatage et de signature sont réunies (zones gelées).", verbose_name='Probant (art. 97)')),
                ('empreinte', models.CharField(blank=True, max_length=128, verbose_name='Empreinte de scellement')),
                ('contenu_json', models.JSONField(default=dict, help_text='Données du certificat au format neutre (§ 6.3) — sert de source canonique pour la génération PDF/A bilingue.', verbose_name='Contenu structuré')),
                ('fichier_pdf', models.FileField(blank=True, upload_to='certificats/%Y/%m/', verbose_name='Fichier PDF')),
            ],
            options={
                'verbose_name': 'Certificat',
                'verbose_name_plural': 'Certificats',
                'ordering': ('-cree_le',),
            },
        ),
    ]
