# Generated by Django 4.2.11 on 2026-04-22 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inscriptions', '0002_initial'),
        ('recherche', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificat',
            name='cree_par',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='certificat',
            name='inscription',
            field=models.ForeignKey(blank=True, help_text='Facultatif pour les certificats de recherche, qui se rattachent à une requête de recherche.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificats', to='inscriptions.inscription', verbose_name='Inscription associée'),
        ),
        migrations.AddField(
            model_name='certificat',
            name='modifie_par',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AddField(
            model_name='certificat',
            name='requete_recherche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificats', to='recherche.requeterecherche', verbose_name='Requête de recherche'),
        ),
    ]
