# Generated by Django 4.2.9 on 2026-04-05 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametrage', '0001_initial'),
        ('entites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistreAnalytique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_ra', models.CharField(max_length=30, unique=True, verbose_name='N° analytique')),
                ('type_entite', models.CharField(choices=[('PH', 'Personne Physique'), ('PM', 'Personne Morale'), ('SC', 'Succursale')], max_length=5)),
                ('numero_rc', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='N° RC')),
                ('date_immatriculation', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('IMMATRICULE', 'Immatriculé'), ('RADIE', 'Radié'), ('SUSPENDU', 'Suspendu'), ('ANNULE', 'Annulé')], db_index=True, default='EN_COURS', max_length=20)),
                ('date_radiation', models.DateField(blank=True, null=True)),
                ('motif_radiation', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ra_crees', to=settings.AUTH_USER_MODEL)),
                ('localite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametrage.localite', verbose_name='Greffe')),
                ('ph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registres', to='entites.personnephysique')),
                ('pm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registres', to='entites.personnemorale')),
                ('sc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registres', to='entites.succursale')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ra_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registre analytique',
                'verbose_name_plural': 'Registre analytique',
                'db_table': 'registre_analytique',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistreChronologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_chrono', models.CharField(max_length=30, unique=True, verbose_name='N° chronologique')),
                ('type_acte', models.CharField(max_length=30)),
                ('date_acte', models.DateField()),
                ('date_enregistrement', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('EN_INSTANCE', 'En instance'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('ANNULE', 'Annulé')], db_index=True, default='EN_INSTANCE', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chrono_crees', to=settings.AUTH_USER_MODEL)),
                ('ra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chronos', to='registres.registreanalytique')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chrono_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registre chronologique',
                'verbose_name_plural': 'Registre chronologique',
                'db_table': 'registre_chronologique',
                'ordering': ['-date_acte'],
            },
        ),
        migrations.CreateModel(
            name='Gerant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_gerant', models.CharField(choices=[('PH', 'Personne Physique'), ('PM', 'Personne Morale')], default='PH', max_length=5)),
                ('nom_gerant', models.CharField(blank=True, max_length=200)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('pouvoirs', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fonction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametrage.fonction')),
                ('nationalite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametrage.nationalite')),
                ('ph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='entites.personnephysique')),
                ('pm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='entites.personnemorale')),
                ('ra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gerants', to='registres.registreanalytique')),
            ],
            options={
                'verbose_name': 'Gérant',
                'verbose_name_plural': 'Gérants',
                'db_table': 'gerants',
            },
        ),
        migrations.CreateModel(
            name='Associe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_associe', models.CharField(choices=[('PH', 'Personne Physique'), ('PM', 'Personne Morale')], default='PH', max_length=5)),
                ('nom_associe', models.CharField(blank=True, max_length=200)),
                ('nombre_parts', models.IntegerField(default=0)),
                ('valeur_parts', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pourcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('type_part', models.CharField(blank=True, max_length=50)),
                ('date_entree', models.DateField(blank=True, null=True)),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nationalite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametrage.nationalite')),
                ('ph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='entites.personnephysique')),
                ('pm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='entites.personnemorale')),
                ('ra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associes', to='registres.registreanalytique')),
            ],
            options={
                'verbose_name': 'Associé',
                'verbose_name_plural': 'Associés',
                'db_table': 'associes',
            },
        ),
        migrations.CreateModel(
            name='RADomaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrage.domaineactivite')),
                ('ra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domaines', to='registres.registreanalytique')),
            ],
            options={
                'db_table': 'ra_domaines',
                'unique_together': {('ra', 'domaine')},
            },
        ),
    ]
