# Generated by Django 4.2.9 on 2026-04-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registres', '0009_declarant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declarant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registreanalytique',
            name='numero_ra',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='N° analytique'),
        ),
    ]
