# Generated by Django 4.2.11 on 2026-04-29 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartenaireBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('code', models.CharField(db_index=True, help_text='Identifiant stable à choisir par le MO (ex. code BCM).', max_length=32, unique=True, verbose_name='Code partenaire (unique)')),
                ('raison_sociale', models.CharField(max_length=255, verbose_name='Raison sociale')),
                ('type_partenaire', models.CharField(choices=[('banque', 'Banque agréée par la BCM'), ('microfinance', 'Institution de microfinance'), ('societe_financiere', 'Société financière'), ('ifi', 'Institution financière internationale')], max_length=24, verbose_name='Type de partenaire')),
                ('statut', models.CharField(choices=[('en_instruction', 'En instruction'), ('agree', 'Agréé'), ('suspendu', 'Suspendu'), ('revoque', 'Révoqué')], default='en_instruction', max_length=24, verbose_name="Statut d'agrément")),
                ('contact_technique_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact technique (e-mail)')),
                ('contact_technique_telephone', models.CharField(blank=True, max_length=32, verbose_name='Contact technique (téléphone)')),
                ('autorite_agrement', models.CharField(blank=True, help_text='Ex. : BCM, Ministère des Finances, …', max_length=128, verbose_name="Autorité d'agrément")),
                ('reference_agrement', models.CharField(blank=True, max_length=128, verbose_name="Référence de l'acte d'agrément")),
                ('valide_du', models.DateField(blank=True, null=True, verbose_name='Valide du')),
                ('valide_au', models.DateField(blank=True, null=True, verbose_name='Valide au')),
                ('note_interne', models.TextField(blank=True, verbose_name='Note interne')),
                ('cree_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('modifie_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Partenaire externe (F15)',
                'verbose_name_plural': 'Partenaires externes (F15)',
                'ordering': ('raison_sociale',),
            },
        ),
        migrations.CreateModel(
            name='ConsentementInterconnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('accorde_le', models.DateTimeField(verbose_name='Accordé le')),
                ('valide_jusquau', models.DateTimeField(blank=True, null=True, verbose_name="Valide jusqu'au")),
                ('revoque_le', models.DateTimeField(blank=True, null=True, verbose_name='Révoqué le')),
                ('motif_revocation', models.CharField(blank=True, max_length=255, verbose_name='Motif de révocation')),
                ('preuve_documentaire', models.CharField(blank=True, help_text='Chemin / hash du document de consentement. La nature du document est à arbitrer en F15 (signature électronique = F3).', max_length=255, verbose_name='Référence de la preuve')),
                ('constituant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consentements_interconnexion', to='parties.partie', verbose_name='Constituant')),
                ('cree_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('modifie_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consentements', to='interconnexions.partenairebancaire', verbose_name='Partenaire')),
            ],
            options={
                'verbose_name': "Consentement d'interconnexion (F15)",
                'verbose_name_plural': "Consentements d'interconnexion (F15)",
            },
        ),
        migrations.CreateModel(
            name='ClePubliquePartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('empreinte_sha256', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Empreinte SHA-256 (hex)')),
                ('sujet_x509', models.CharField(blank=True, max_length=255, verbose_name='Sujet X.509')),
                ('emetteur_x509', models.CharField(blank=True, max_length=255, verbose_name='Émetteur X.509')),
                ('valide_du', models.DateField(verbose_name='Valide du')),
                ('valide_au', models.DateField(verbose_name='Valide au')),
                ('revoquee', models.BooleanField(default=False, verbose_name='Révoquée')),
                ('motif_revocation', models.CharField(blank=True, max_length=255, verbose_name='Motif de révocation')),
                ('cree_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('modifie_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cles', to='interconnexions.partenairebancaire', verbose_name='Partenaire')),
            ],
            options={
                'verbose_name': 'Clé publique partenaire (F15)',
                'verbose_name_plural': 'Clés publiques partenaires (F15)',
            },
        ),
        migrations.CreateModel(
            name='AccreditationPartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('reference_convention', models.CharField(db_index=True, max_length=128, verbose_name='Référence de la convention')),
                ('debut_le', models.DateField(verbose_name='Début')),
                ('fin_le', models.DateField(blank=True, null=True, verbose_name='Fin')),
                ('plafond_requetes_par_jour', models.PositiveIntegerField(default=0, help_text='0 = illimité (à éviter — décision F15 #7).', verbose_name='Plafond de requêtes par jour')),
                ('perimetre', models.JSONField(default=dict, help_text="Décrit les champs accessibles au partenaire. Tant que la fiche F15 #4 n'est pas tranchée, ce champ reste vide ; aucune ouverture par défaut.", verbose_name='Périmètre de données autorisées')),
                ('actif', models.BooleanField(default=False, verbose_name='Accréditation active')),
                ('cree_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('modifie_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accreditations', to='interconnexions.partenairebancaire', verbose_name='Partenaire')),
            ],
            options={
                'verbose_name': 'Accréditation partenaire (F15)',
                'verbose_name_plural': 'Accréditations partenaires (F15)',
                'ordering': ('-debut_le',),
            },
        ),
        migrations.CreateModel(
            name='JournalAccesAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instant', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Instant')),
                ('methode', models.CharField(max_length=8, verbose_name='Méthode HTTP')),
                ('chemin', models.CharField(max_length=255, verbose_name='Chemin')),
                ('parametres', models.JSONField(default=dict, help_text="Critères de recherche art. 96 ou payload résumé. Aucune donnée personnelle hors article 96 n'est journalisée.", verbose_name='Paramètres envoyés')),
                ('code_retour', models.PositiveSmallIntegerField(verbose_name='Code HTTP retour')),
                ('certificat_emis', models.CharField(blank=True, max_length=128, verbose_name='Identifiant de certificat émis (art. 97)')),
                ('duree_ms', models.PositiveIntegerField(default=0, verbose_name='Durée (ms)')),
                ('ip_origine', models.GenericIPAddressField(blank=True, null=True, verbose_name="IP d'origine")),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User-Agent')),
                ('cle_utilisee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_acces', to='interconnexions.clepubliquepartenaire', verbose_name='Clé utilisée')),
                ('partenaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_acces', to='interconnexions.partenairebancaire', verbose_name='Partenaire')),
            ],
            options={
                'verbose_name': "Entrée du journal d'accès API (F15)",
                'verbose_name_plural': "Entrées du journal d'accès API (F15)",
                'ordering': ('-instant',),
                'indexes': [models.Index(fields=['partenaire', 'instant'], name='interconnex_partena_49f449_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='consentementinterconnexion',
            constraint=models.UniqueConstraint(condition=models.Q(('revoque_le__isnull', True)), fields=('constituant', 'partenaire'), name='unique_consentement_actif'),
        ),
    ]
