# Generated by Django 4.2.11 on 2026-04-22 01:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BienGreve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('description_fr', models.TextField(blank=True, verbose_name='Description (français)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (arabe)')),
                ('langue_faisant_foi_description', models.CharField(choices=[('fr', 'Français'), ('ar', 'Arabe'), ('equ', 'Équivalent établi FR et AR')], default='equ', max_length=3, verbose_name='Langue faisant foi (description)')),
                ('actif', models.BooleanField(db_index=True, default=True, help_text="Un enregistrement inactif reste conservé (art. 79) mais n'apparaît plus au fichier public comme faisant partie de l'inscription en cours.", verbose_name='Actif')),
                ('date_fin_validite', models.DateTimeField(blank=True, null=True, verbose_name='Fin de validité')),
                ('raison_fin', models.CharField(blank=True, help_text="Référence métier (ex. ``modification.N°``, ``radiation.N°``) à rapprocher du journal d'audit.", max_length=255, verbose_name='Raison de fin de validité')),
                ('marque', models.CharField(blank=True, max_length=128, verbose_name='Marque / fabricant')),
                ('modele', models.CharField(blank=True, max_length=128, verbose_name='Modèle')),
                ('annee', models.PositiveIntegerField(blank=True, null=True, verbose_name='Année')),
                ('numero_serie', models.CharField(blank=True, db_index=True, help_text="Article 93 — indexation additionnelle pour les biens porteurs d'un numéro de série.", max_length=128, verbose_name='Numéro de série')),
            ],
            options={
                'verbose_name': 'Bien grevé',
                'verbose_name_plural': 'Biens grevés',
            },
        ),
    ]
