# Generated by Django 4.2.11 on 2026-04-22 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inscriptions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biengreve',
            name='cree_par',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='biengreve',
            name='inscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biens', to='inscriptions.inscription', verbose_name='Inscription rattachée'),
        ),
        migrations.AddField(
            model_name='biengreve',
            name='modifie_par',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AddIndex(
            model_name='biengreve',
            index=models.Index(fields=['numero_serie'], name='biens_bieng_numero__d178fe_idx'),
        ),
        migrations.AddIndex(
            model_name='biengreve',
            index=models.Index(fields=['marque', 'modele'], name='biens_bieng_marque_5f490c_idx'),
        ),
        migrations.AddIndex(
            model_name='biengreve',
            index=models.Index(fields=['inscription', 'actif'], name='biens_bieng_inscrip_3644fc_idx'),
        ),
    ]
