# Generated by Django 4.2.11 on 2026-04-30 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biens', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('cle', models.CharField(db_index=True, help_text="Identifiant slug stable d'une version à l'autre (ex. ``vehicules``, ``stocks_marchandises``).", max_length=64, verbose_name='Clé technique stable')),
                ('version', models.PositiveIntegerField(default=1, help_text='Incrémentée à chaque modification du schéma. Versions antérieures conservées (non rétroactivité).', verbose_name='Version')),
                ('libelle_fr', models.CharField(max_length=255, verbose_name='Libellé (FR)')),
                ('libelle_ar', models.CharField(max_length=255, verbose_name='Libellé (AR)')),
                ('description_fr', models.TextField(blank=True, verbose_name='Description (FR)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (AR)')),
                ('schema_champs', models.JSONField(default=list, help_text='Liste ordonnée de descripteurs de champs. Chaque descripteur porte cle, type, obligatoire, libelle_fr, libelle_ar.', verbose_name='Schéma des champs spécifiques')),
                ('affichage_observations', models.BooleanField(default=True, help_text="Le document MO précise les catégories pour lesquelles le champ Observations doit être affiché. Lorsque False, le champ n'est pas exposé à la saisie.", verbose_name='Champ « Observations » affiché')),
                ('actif', models.BooleanField(default=True, help_text='Une seule version peut être active à la fois pour une cle donnée. Les versions précédentes restent disponibles pour lecture des anciens biens.', verbose_name='Version active')),
            ],
            options={
                'verbose_name': 'Catégorie de bien',
                'verbose_name_plural': 'Catégories de biens',
                'ordering': ('libelle_fr', 'version'),
            },
        ),
        migrations.AddField(
            model_name='biengreve',
            name='attributs_specifiques',
            field=models.JSONField(blank=True, default=dict, help_text='Dictionnaire {cle: valeur} validé contre le schéma de la catégorie+version ci-dessus. Toute clé non prévue est rejetée.', verbose_name='Attributs spécifiques'),
        ),
        migrations.AddField(
            model_name='biengreve',
            name='categorie_cle',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Catégorie (clé)'),
        ),
        migrations.AddField(
            model_name='biengreve',
            name='categorie_version_snapshot',
            field=models.PositiveIntegerField(default=0, help_text='Version de la catégorie utilisée à la saisie. Garantit la non-rétroactivité : aucune mise à jour de schéma ne modifie les biens déjà inscrits.', verbose_name='Version du schéma au dépôt'),
        ),
        migrations.AddField(
            model_name='biengreve',
            name='observations',
            field=models.TextField(blank=True, help_text='Champ libre, présent uniquement pour les catégories dont ``CategorieBien.affichage_observations`` vaut True.', verbose_name='Observations'),
        ),
        migrations.AddIndex(
            model_name='biengreve',
            index=models.Index(fields=['categorie_cle', 'categorie_version_snapshot'], name='biens_bieng_categor_c8f866_idx'),
        ),
        migrations.AddField(
            model_name='categoriebien',
            name='cree_par',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='categoriebien',
            name='modifie_par',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AddConstraint(
            model_name='categoriebien',
            constraint=models.UniqueConstraint(fields=('cle', 'version'), name='unique_categorie_cle_version'),
        ),
        migrations.AddConstraint(
            model_name='categoriebien',
            constraint=models.UniqueConstraint(condition=models.Q(('actif', True)), fields=('cle',), name='unique_categorie_active_par_cle'),
        ),
    ]
