"""
Seed des 18 catégories de biens conformément au document MO
« Liste des catégories de biens et éléments de description ».

Aucune invention : libellés, ordre des champs, types et présence du
champ Observations sont strictement repris du document.

Migration de DONNÉES — exécutée une fois, idempotente :
- crée la version 1 de chaque catégorie si absente ;
- ne touche pas aux versions ultérieures éventuelles.
"""
from django.db import migrations


# Chaque entrée respecte exactement les champs du document MO.
# Le champ « Observations » est ajouté ou non selon la liste fournie
# (présent partout sauf : matériels informatiques, meubles meublants,
# produits liquides non comestibles, produits textiles, produits
# alimentaires, autres). Pour la catégorie « Autres », le document
# remplace Observations par « Autres informations pertinentes » :
# nous le matérialisons par un champ texte_long dédié.
CATEGORIES = [
    {
        "cle": "vehicules",
        "libelle_fr": "Véhicules",
        "libelle_ar": "المركبات",
        "schema_champs": [
            {"cle": "numero_chassis", "type": "texte", "obligatoire": False,
             "libelle_fr": "Numéro de châssis", "libelle_ar": "رقم الهيكل"},
            {"cle": "numero_immatriculation", "type": "texte", "obligatoire": False,
             "libelle_fr": "Numéro d'immatriculation", "libelle_ar": "رقم التسجيل"},
            {"cle": "marque", "type": "texte", "obligatoire": False,
             "libelle_fr": "Marque", "libelle_ar": "العلامة التجارية"},
            {"cle": "modele", "type": "texte", "obligatoire": False,
             "libelle_fr": "Modèle", "libelle_ar": "الطراز"},
            {"cle": "annee_fabrication", "type": "nombre", "obligatoire": False,
             "libelle_fr": "Année de fabrication", "libelle_ar": "سنة الصنع"},
        ],
        "affichage_observations": True,
    },
    {
        "cle": "materiel_professionnel",
        "libelle_fr": "Matériel professionnel",
        "libelle_ar": "المعدات المهنية",
        "schema_champs": [
            {"cle": "description_equipement", "type": "texte_long", "obligatoire": False,
             "libelle_fr": "Description détaillée de l'équipement",
             "libelle_ar": "وصف تفصيلي للمعدة"},
            {"cle": "marque", "type": "texte", "obligatoire": False,
             "libelle_fr": "Marque", "libelle_ar": "العلامة التجارية"},
            {"cle": "modele", "type": "texte", "obligatoire": False,
             "libelle_fr": "Modèle", "libelle_ar": "الطراز"},
            {"cle": "valeur_estimee", "type": "montant", "obligatoire": False,
             "libelle_fr": "Valeur estimée", "libelle_ar": "القيمة المقدَّرة"},
        ],
        "affichage_observations": True,
    },
    {
        "cle": "stocks_marchandises",
        "libelle_fr": "Stocks et marchandises",
        "libelle_ar": "المخزونات والبضائع",
        "schema_champs": [
            {"cle": "type", "type": "texte", "obligatoire": False,
             "libelle_fr": "Type", "libelle_ar": "النوع"},
            {"cle": "quantite", "type": "nombre", "obligatoire": False,
             "libelle_fr": "Quantité", "libelle_ar": "الكمية"},
            {"cle": "valeur_unitaire", "type": "montant", "obligatoire": False,
             "libelle_fr": "Valeur unitaire", "libelle_ar": "القيمة الوحدوية"},
            {"cle": "valeur_totale_stock", "type": "montant", "obligatoire": False,
             "libelle_fr": "Valeur totale du stock", "libelle_ar": "القيمة الإجمالية للمخزون"},
            {"cle": "etat", "type": "texte", "obligatoire": False,
             "libelle_fr": "État (neuf ou d'occasion)",
             "libelle_ar": "الحالة (جديد أو مستعمل)"},
            {"cle": "emplacement_stockage", "type": "texte", "obligatoire": False,
             "libelle_fr": "Emplacement de stockage", "libelle_ar": "مكان التخزين"},
        ],
        "affichage_observations": True,
    },
    {
        "cle": "matieres_premieres",
        "libelle_fr": "Matières premières",
        "libelle_ar": "المواد الأولية",
        "schema_champs": [
            {"cle": "description_matiere", "type": "texte_long", "obligatoire": False,
             "libelle_fr": "Description de la matière", "libelle_ar": "وصف المادة"},
            {"cle": "quantite", "type": "nombre", "obligatoire": False,
             "libelle_fr": "Quantité", "libelle_ar": "الكمية"},
            {"cle": "unite_mesure", "type": "texte", "obligatoire": False,
             "libelle_fr": "Unité de mesure", "libelle_ar": "وحدة القياس"},
            {"cle": "valeur_unitaire", "type": "montant", "obligatoire": False,
             "libelle_fr": "Valeur unitaire", "libelle_ar": "القيمة الوحدوية"},
            {"cle": "valeur_totale", "type": "montant", "obligatoire": False,
             "libelle_fr": "Valeur totale", "libelle_ar": "القيمة الإجمالية"},
            {"cle": "emplacement_stockage", "type": "texte", "obligatoire": False,
             "libelle_fr": "Emplacement de stockage", "libelle_ar": "مكان التخزين"},
        ],
        "affichage_observations": True,
    },
    {
        "cle": "objets_de_valeur",
        "libelle_fr": "Objets de valeur",
        "libelle_ar": "الأشياء الثمينة",
        "schema_champs": [
            {"cle": "description_objet", "type": "texte_long", "obligatoire": False,
             "libelle_fr": "Description détaillée de l'objet",
             "libelle_ar": "وصف تفصيلي للشيء"},
            {"cle": "type_materiau", "type": "texte", "obligatoire": False,
             "libelle_fr": "Type de matériau", "libelle_ar": "نوع المادة"},
            {"cle": "poids", "type": "texte", "obligatoire": False,
             "libelle_fr": "Poids (le cas échéant)",
             "libelle_ar": "الوزن (عند الاقتضاء)"},
            {"cle": "evaluation_valeur", "type": "montant", "obligatoire": False,
             "libelle_fr": "Évaluation de la valeur", "libelle_ar": "تقدير القيمة"},
            {"cle": "etat_objet", "type": "texte", "obligatoire": False,
             "libelle_fr": "État de l'objet", "libelle_ar": "حالة الشيء"},
        ],
        "affichage_observations": True,
    },
    {
        "cle": "animaux",
        "libelle_fr": "Animaux",
        "libelle_ar": "الحيوانات",
        "schema_champs": [
            {"cle": "espece", "type": "texte", "obligatoire": False,
             "libelle_fr": "Espèce", "libelle_ar": "الفصيلة"},
            {"cle": "race", "type": "texte", "obligatoire": False,
             "libelle_fr": "Race", "libelle_ar": "السلالة"},
            {"cle": "evaluation_valeur", "type": "montant", "obligatoire": False,
             "libelle_fr": "Évaluation de la valeur", "libelle_ar": "تقدير القيمة"},
        ],
        "affichage_observations": True,
    },
    {
        "cle": "creances",
        "libelle_fr": "Créances",
        "libelle_ar": "الديون",
        "schema_champs": [
            {"cle": "nom_debiteur", "type": "texte", "obligatoire": False,
             "libelle_fr": "Nom du débiteur", "libelle_ar": "اسم المدين"},
            {"cle": "montant_du", "type": "montant", "obligatoire": False,
             "libelle_fr": "Montant dû", "libelle_ar": "المبلغ المستحق"},
            {"cle": "date_echeance", "type": "date", "obligatoire": False,
             "libelle_fr": "Date d'échéance", "libelle_ar": "تاريخ الاستحقاق"},
            {"cle": "nature_creance", "type": "texte", "obligatoire": False,
             "libelle_fr": "Nature de la créance (prêt, facture, etc.)",
             "libelle_ar": "طبيعة الدين (قرض، فاتورة، إلخ)"},
            {"cle": "existence_garanties", "type": "texte_long", "obligatoire": False,
             "libelle_fr": "Existence de garanties", "libelle_ar": "وجود ضمانات"},
        ],
        "affichage_observations": True,
    },
    {
        "cle": "brevets_propriete_intellectuelle",
        "libelle_fr": "Brevets et droits de propriété intellectuelle",
        "libelle_ar": "البراءات وحقوق الملكية الفكرية",
        "schema_champs": [
            {"cle": "numero_brevet", "type": "texte", "obligatoire": False,
             "libelle_fr": "Numéro de brevet", "libelle_ar": "رقم البراءة"},
            {"cle": "description_invention", "type": "texte_long", "obligatoire": False,
             "libelle_fr": "Description de l'invention",
             "libelle_ar": "وصف الاختراع"},
            {"cle": "date_delivrance", "type": "date", "obligatoire": False,
             "libelle_fr": "Date de délivrance", "libelle_ar": "تاريخ المنح"},
            {"cle": "duree_validite_restante", "type": "texte", "obligatoire": False,
             "libelle_fr": "Durée de validité restante",
             "libelle_ar": "المدة المتبقية من الصلاحية"},
            {"cle": "titulaire_brevet", "type": "texte", "obligatoire": False,
             "libelle_fr": "Titulaire du brevet", "libelle_ar": "صاحب البراءة"},
        ],
        "affichage_observations": True,
    },
    {
        "cle": "droits_auteur",
        "libelle_fr": "Droits d'auteur",
        "libelle_ar": "حقوق المؤلف",
        "schema_champs": [
            {"cle": "titre_oeuvre", "type": "texte", "obligatoire": False,
             "libelle_fr": "Titre de l'œuvre", "libelle_ar": "عنوان المُصنَّف"},
            {"cle": "nom_auteur", "type": "texte", "obligatoire": False,
             "libelle_fr": "Nom de l'auteur", "libelle_ar": "اسم المؤلف"},
            {"cle": "date_creation", "type": "date", "obligatoire": False,
             "libelle_fr": "Date de création", "libelle_ar": "تاريخ الإنشاء"},
            {"cle": "date_enregistrement_droit_auteur", "type": "date",
             "obligatoire": False,
             "libelle_fr": "Date d'enregistrement du droit d'auteur",
             "libelle_ar": "تاريخ تسجيل حق المؤلف"},
        ],
        "affichage_observations": True,
    },
    {
        "cle": "fonds_de_commerce",
        "libelle_fr": "Fonds de commerce",
        "libelle_ar": "الأصل التجاري",
        "schema_champs": [
            {"cle": "description_activite", "type": "texte_long", "obligatoire": False,
             "libelle_fr": "Description de l'activité", "libelle_ar": "وصف النشاط"},
            {"cle": "liste_actifs", "type": "texte_long", "obligatoire": False,
             "libelle_fr": "Liste des actifs compris dans le fonds de commerce",
             "libelle_ar": "قائمة الأصول المشمولة بالأصل التجاري"},
            {"cle": "chiffre_affaires", "type": "montant", "obligatoire": False,
             "libelle_fr": "Chiffre d'affaires", "libelle_ar": "رقم الأعمال"},
            {"cle": "benefices", "type": "montant", "obligatoire": False,
             "libelle_fr": "Bénéfices", "libelle_ar": "الأرباح"},
        ],
        "affichage_observations": True,
    },
    {
        "cle": "droits_associes",
        "libelle_fr": "Droits d'associés (parts sociales ou actions)",
        "libelle_ar": "حقوق الشركاء (الحصص الاجتماعية أو الأسهم)",
        "schema_champs": [
            {"cle": "nom_societe", "type": "texte", "obligatoire": False,
             "libelle_fr": "Nom de la société", "libelle_ar": "اسم الشركة"},
            {"cle": "type_participation", "type": "texte", "obligatoire": False,
             "libelle_fr": "Type de participation (actions, parts sociales)",
             "libelle_ar": "نوع المشاركة (أسهم، حصص اجتماعية)"},
            {"cle": "nombre_titres_detenus", "type": "nombre", "obligatoire": False,
             "libelle_fr": "Nombre de titres détenus",
             "libelle_ar": "عدد السندات المملوكة"},
            {"cle": "pourcentage_possession", "type": "nombre", "obligatoire": False,
             "libelle_fr": "Pourcentage de possession",
             "libelle_ar": "نسبة الملكية"},
            {"cle": "valeur_nominale", "type": "montant", "obligatoire": False,
             "libelle_fr": "Valeur nominale", "libelle_ar": "القيمة الاسمية"},
        ],
        "affichage_observations": True,
    },
    {
        "cle": "comptes_bancaires",
        "libelle_fr": "Comptes bancaires",
        "libelle_ar": "الحسابات المصرفية",
        "schema_champs": [
            {"cle": "nom_titulaire", "type": "texte", "obligatoire": False,
             "libelle_fr": "Nom du titulaire du compte",
             "libelle_ar": "اسم صاحب الحساب"},
            {"cle": "numero_compte", "type": "texte", "obligatoire": False,
             "libelle_fr": "Numéro de compte", "libelle_ar": "رقم الحساب"},
            {"cle": "nom_banque", "type": "texte", "obligatoire": False,
             "libelle_fr": "Nom de la banque", "libelle_ar": "اسم البنك"},
            {"cle": "type_compte", "type": "texte", "obligatoire": False,
             "libelle_fr": "Type de compte (courant, épargne, etc.)",
             "libelle_ar": "نوع الحساب (جاري، توفير، إلخ)"},
            {"cle": "solde_actuel", "type": "montant", "obligatoire": False,
             "libelle_fr": "Solde actuel", "libelle_ar": "الرصيد الحالي"},
        ],
        "affichage_observations": True,
    },
    {
        "cle": "materiels_informatiques",
        "libelle_fr": "Matériels informatiques et accessoires",
        "libelle_ar": "المعدات المعلوماتية والملحقات",
        "schema_champs": [
            {"cle": "marque", "type": "texte", "obligatoire": False,
             "libelle_fr": "Marque", "libelle_ar": "العلامة التجارية"},
            {"cle": "modele", "type": "texte", "obligatoire": False,
             "libelle_fr": "Modèle", "libelle_ar": "الطراز"},
            {"cle": "specifications_techniques", "type": "texte_long", "obligatoire": False,
             "libelle_fr": "Spécifications techniques (processeur, mémoire, stockage, etc.)",
             "libelle_ar": "المواصفات التقنية (المعالج، الذاكرة، التخزين، إلخ)"},
            {"cle": "etat", "type": "texte", "obligatoire": False,
             "libelle_fr": "État (neuf, d'occasion, rénové)",
             "libelle_ar": "الحالة (جديد، مستعمل، مجدَّد)"},
            {"cle": "quantite", "type": "nombre", "obligatoire": False,
             "libelle_fr": "Quantité", "libelle_ar": "الكمية"},
        ],
        "affichage_observations": False,
    },
    {
        "cle": "meubles_meublants",
        "libelle_fr": "Meubles meublants",
        "libelle_ar": "الأثاث",
        "schema_champs": [
            {"cle": "type_meuble", "type": "texte", "obligatoire": False,
             "libelle_fr": "Type de meuble (chaise, table, armoire, etc.)",
             "libelle_ar": "نوع الأثاث (كرسي، طاولة، خزانة، إلخ)"},
            {"cle": "materiel_fabrication", "type": "texte", "obligatoire": False,
             "libelle_fr": "Matériel de fabrication (bois, métal, etc.)",
             "libelle_ar": "مادة الصنع (خشب، معدن، إلخ)"},
            {"cle": "style", "type": "texte", "obligatoire": False,
             "libelle_fr": "Style (moderne, antique)",
             "libelle_ar": "الطراز (حديث، عتيق)"},
            {"cle": "dimensions", "type": "texte", "obligatoire": False,
             "libelle_fr": "Dimensions (hauteur, largeur)",
             "libelle_ar": "الأبعاد (الارتفاع، العرض)"},
            {"cle": "etat", "type": "texte", "obligatoire": False,
             "libelle_fr": "État (neuf, d'occasion, restauré, etc.)",
             "libelle_ar": "الحالة (جديد، مستعمل، مرمَّم، إلخ)"},
        ],
        "affichage_observations": False,
    },
    {
        "cle": "produits_liquides_non_comestibles",
        "libelle_fr": "Produits liquides non comestibles",
        "libelle_ar": "المنتجات السائلة غير الصالحة للأكل",
        "schema_champs": [
            {"cle": "nature_liquide", "type": "texte", "obligatoire": False,
             "libelle_fr": "Nature du liquide (par exemple, produits de nettoyage, carburant, etc.)",
             "libelle_ar": "طبيعة السائل (مثلاً منتجات تنظيف، وقود، إلخ)"},
            {"cle": "marque", "type": "texte", "obligatoire": False,
             "libelle_fr": "Marque (le cas échéant)",
             "libelle_ar": "العلامة التجارية (عند الاقتضاء)"},
            {"cle": "volume", "type": "texte", "obligatoire": False,
             "libelle_fr": "Volume (en litres, gallons, etc.)",
             "libelle_ar": "الحجم (لتر، غالون، إلخ)"},
            {"cle": "emballage", "type": "texte", "obligatoire": False,
             "libelle_fr": "Emballage (bouteille en plastique, jerrican en métal, etc.)",
             "libelle_ar": "التعبئة (قارورة بلاستيكية، جيريكان معدني، إلخ)"},
        ],
        "affichage_observations": False,
    },
    {
        "cle": "produits_textiles",
        "libelle_fr": "Produits textiles",
        "libelle_ar": "المنتجات النسيجية",
        "schema_champs": [
            {"cle": "type_textile", "type": "texte", "obligatoire": False,
             "libelle_fr": "Type de textile (coton, laine, synthétique, etc.)",
             "libelle_ar": "نوع النسيج (قطن، صوف، اصطناعي، إلخ)"},
            {"cle": "article", "type": "texte", "obligatoire": False,
             "libelle_fr": "Article (vêtement, linge de maison, etc.)",
             "libelle_ar": "المادة (ملابس، أغطية منزلية، إلخ)"},
            {"cle": "taille", "type": "texte", "obligatoire": False,
             "libelle_fr": "Taille (le cas échéant)",
             "libelle_ar": "المقاس (عند الاقتضاء)"},
            {"cle": "couleur", "type": "texte", "obligatoire": False,
             "libelle_fr": "Couleur", "libelle_ar": "اللون"},
            {"cle": "marque_fabricant", "type": "texte", "obligatoire": False,
             "libelle_fr": "Marque ou fabricant",
             "libelle_ar": "العلامة التجارية أو الصانع"},
            {"cle": "etat", "type": "texte", "obligatoire": False,
             "libelle_fr": "État (neuf, d'occasion, vintage)",
             "libelle_ar": "الحالة (جديد، مستعمل، فينتاج)"},
        ],
        "affichage_observations": False,
    },
    {
        "cle": "produits_alimentaires",
        "libelle_fr": "Produits alimentaires",
        "libelle_ar": "المنتجات الغذائية",
        "schema_champs": [
            {"cle": "type_produit", "type": "texte", "obligatoire": False,
             "libelle_fr": "Type de produit (conserves, produits frais, etc.)",
             "libelle_ar": "نوع المنتج (محفوظات، منتجات طازجة، إلخ)"},
            {"cle": "marque", "type": "texte", "obligatoire": False,
             "libelle_fr": "Marque", "libelle_ar": "العلامة التجارية"},
            {"cle": "date_peremption", "type": "date", "obligatoire": False,
             "libelle_fr": "Date de péremption (le cas échéant)",
             "libelle_ar": "تاريخ انتهاء الصلاحية (عند الاقتضاء)"},
            {"cle": "emballage", "type": "texte", "obligatoire": False,
             "libelle_fr": "Emballage (boîte, sachet, bocal en verre, etc.)",
             "libelle_ar": "التعبئة (علبة، كيس، وعاء زجاجي، إلخ)"},
            {"cle": "quantite", "type": "texte", "obligatoire": False,
             "libelle_fr": "Quantité (poids, volume, nombre d'unités)",
             "libelle_ar": "الكمية (الوزن، الحجم، عدد الوحدات)"},
        ],
        "affichage_observations": False,
    },
    {
        "cle": "autres",
        "libelle_fr": "Autres",
        "libelle_ar": "أخرى",
        "schema_champs": [
            {"cle": "type_bien", "type": "texte", "obligatoire": False,
             "libelle_fr": "Type de bien", "libelle_ar": "نوع المال"},
            {"cle": "description_detaillee", "type": "texte_long", "obligatoire": False,
             "libelle_fr": "Description détaillée", "libelle_ar": "وصف تفصيلي"},
            {"cle": "etat", "type": "texte", "obligatoire": False,
             "libelle_fr": "État", "libelle_ar": "الحالة"},
            {"cle": "marque_fabricant", "type": "texte", "obligatoire": False,
             "libelle_fr": "Marque ou fabricant",
             "libelle_ar": "العلامة التجارية أو الصانع"},
            {"cle": "quantite", "type": "nombre", "obligatoire": False,
             "libelle_fr": "Quantité", "libelle_ar": "الكمية"},
            {"cle": "emplacement_actuel", "type": "texte", "obligatoire": False,
             "libelle_fr": "Emplacement actuel", "libelle_ar": "الموقع الحالي"},
            {"cle": "autres_informations", "type": "texte_long", "obligatoire": False,
             "libelle_fr": "Autres informations pertinentes",
             "libelle_ar": "معلومات أخرى ذات صلة"},
        ],
        "affichage_observations": False,
    },
]


def seed_categories(apps, schema_editor):
    CategorieBien = apps.get_model("biens", "CategorieBien")
    for cfg in CATEGORIES:
        CategorieBien.objects.get_or_create(
            cle=cfg["cle"], version=1,
            defaults={
                "libelle_fr": cfg["libelle_fr"],
                "libelle_ar": cfg["libelle_ar"],
                "schema_champs": cfg["schema_champs"],
                "affichage_observations": cfg["affichage_observations"],
                "actif": True,
                "description_fr": "",
                "description_ar": "",
            },
        )


def reverse_seed(apps, schema_editor):
    CategorieBien = apps.get_model("biens", "CategorieBien")
    cles = [c["cle"] for c in CATEGORIES]
    CategorieBien.objects.filter(cle__in=cles, version=1).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("biens", "0003_categoriebien_biengreve_attributs_specifiques_and_more"),
    ]
    operations = [
        migrations.RunPython(seed_categories, reverse_seed),
    ]
