# Generated by Django 4.2.9 on 2026-04-05 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_modif', models.CharField(max_length=30, unique=True)),
                ('date_modif', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée'), ('ANNULEE', 'Annulée')], db_index=True, default='EN_COURS', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('chrono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registres.registrechronologique')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifs_creees', to=settings.AUTH_USER_MODEL)),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demandes.demande')),
                ('ra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modifications', to='registres.registreanalytique')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifs_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modification',
                'verbose_name_plural': 'Modifications',
                'db_table': 'modifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_champ', models.CharField(blank=True, max_length=50)),
                ('libelle_champ', models.CharField(blank=True, max_length=200)),
                ('ancienne_valeur', models.TextField(blank=True)),
                ('nouvelle_valeur', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='modifications.modification')),
            ],
            options={
                'verbose_name': 'Ligne modification',
                'verbose_name_plural': 'Lignes modification',
                'db_table': 'lignes_modification',
            },
        ),
    ]
