# Generated by Django 4.2.9 on 2026-04-06 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modifications', '0002_modification_workflow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lignemodification',
            options={},
        ),
        migrations.AlterField(
            model_name='lignemodification',
            name='code_champ',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lignemodification',
            name='libelle_champ',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='modification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='modification',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications_validees', to=settings.AUTH_USER_MODEL),
        ),
    ]
