# Generated by Django 4.2.9 on 2026-04-05 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_depot', models.CharField(max_length=30, unique=True)),
                ('type_depot', models.CharField(blank=True, max_length=50)),
                ('annee_exercice', models.IntegerField(blank=True, null=True)),
                ('date_depot', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ENREGISTRE', 'Enregistré'), ('REJETE', 'Rejeté'), ('ANNULE', 'Annulé')], db_index=True, default='EN_ATTENTE', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depots_crees', to=settings.AUTH_USER_MODEL)),
                ('ra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depots', to='registres.registreanalytique')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depots_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dépôt',
                'verbose_name_plural': 'Dépôts',
                'db_table': 'depots',
                'ordering': ['-created_at'],
            },
        ),
    ]
