# Generated by Django 4.2.11 on 2026-04-22 01:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeRenouvellement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('statut', models.CharField(choices=[('recue', 'Reçue'), ('rejetee', 'Rejetée (hors délai — art. 91)'), ('appliquee', 'Appliquée')], default='recue', max_length=16, verbose_name='Statut')),
                ('motif_refus', models.CharField(blank=True, max_length=255, verbose_name='Motif de refus')),
                ('ancienne_date_expiration', models.DateField(blank=True, null=True, verbose_name="Ancienne date d'expiration")),
                ('nouvelle_date_expiration', models.DateField(blank=True, null=True, verbose_name="Nouvelle date d'expiration")),
                ('applique_le', models.DateTimeField(blank=True, null=True, verbose_name='Appliquée le')),
            ],
            options={
                'verbose_name': 'Demande de renouvellement',
                'verbose_name_plural': 'Demandes de renouvellement',
                'ordering': ('-cree_le',),
            },
        ),
    ]
