# Generated by Django 4.2.11 on 2026-04-22 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('renouvellements', '0001_initial'),
        ('inscriptions', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanderenouvellement',
            name='cree_par',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='demanderenouvellement',
            name='inscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_renouvellement', to='inscriptions.inscription', verbose_name='Inscription'),
        ),
        migrations.AddField(
            model_name='demanderenouvellement',
            name='modifie_par',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
    ]
