# Generated by Django 4.2.9 on 2026-04-06 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modifications', '0003_document_modification_cession'),
        ('cessions', '0004_document_modification_cession'),
        ('documents', '0002_document_add_rbe_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='cessions.cession'),
        ),
        migrations.AddField(
            model_name='document',
            name='modification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='modifications.modification'),
        ),
    ]
