# Generated by Django 4.2.11 on 2026-04-22 01:49

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('identifiant_officiel', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Identifiant officiel')),
                ('nom_affichage', models.CharField(blank=True, max_length=200, verbose_name="Nom d'affichage")),
                ('telephone', models.CharField(blank=True, max_length=32, verbose_name='Téléphone')),
                ('compte_actif', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AffectationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('agent_saisie', 'Agent de saisie (Greffe)'), ('autorite_validation', 'Autorité de validation (Greffier)'), ('admin_fonctionnel', 'Administrateur fonctionnel'), ('admin_technique', 'Administrateur technique'), ('auditeur', 'Auditeur / Contrôleur'), ('prod_stats', 'Producteur de statistiques (Greffe)'), ('declarant_externe', 'Déclarant externe authentifié')], max_length=32, verbose_name='Rôle')),
                ('actif', models.BooleanField(default=True, verbose_name='Affectation active')),
                ('debut_le', models.DateTimeField(auto_now_add=True, verbose_name="Début d'affectation")),
                ('fin_le', models.DateTimeField(blank=True, null=True, verbose_name="Fin d'affectation")),
                ('motif_affectation', models.CharField(blank=True, max_length=255, verbose_name="Motif d'affectation ou de révocation")),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_role', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Affectation de rôle',
                'verbose_name_plural': 'Affectations de rôles',
            },
        ),
        migrations.AddConstraint(
            model_name='affectationrole',
            constraint=models.UniqueConstraint(condition=models.Q(('actif', True)), fields=('utilisateur', 'role'), name='unique_role_actif_par_utilisateur'),
        ),
    ]
