# Generated by Django 4.2.11 on 2026-04-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='mot_de_passe_initial',
            field=models.BooleanField(default=False, verbose_name='Mot de passe initial à changer'),
        ),
    ]
