# Generated by Django 4.2.9 on 2026-04-05 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomaineActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle_fr', models.CharField(max_length=200)),
                ('libelle_ar', models.CharField(blank=True, max_length=200)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Domaine d'activité",
                'verbose_name_plural': "Domaines d'activités",
                'db_table': 'domaines_activites',
                'ordering': ['libelle_fr'],
            },
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle_fr', models.CharField(max_length=100)),
                ('libelle_ar', models.CharField(blank=True, max_length=100)),
                ('type_entite', models.CharField(choices=[('PH', 'PH'), ('PM', 'PM'), ('SC', 'SC'), ('ALL', 'Tous')], default='ALL', max_length=5)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fonction',
                'verbose_name_plural': 'Fonctions',
                'db_table': 'fonctions',
                'ordering': ['libelle_fr'],
            },
        ),
        migrations.CreateModel(
            name='FormeJuridique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle_fr', models.CharField(max_length=150)),
                ('libelle_ar', models.CharField(blank=True, max_length=150)),
                ('type_entite', models.CharField(choices=[('PH', 'Personne Physique'), ('PM', 'Personne Morale'), ('SC', 'Succursale'), ('ALL', 'Tous')], default='ALL', max_length=5)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Forme juridique',
                'verbose_name_plural': 'Formes juridiques',
                'db_table': 'formes_juridiques',
                'ordering': ['libelle_fr'],
            },
        ),
        migrations.CreateModel(
            name='Nationalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('libelle_fr', models.CharField(max_length=100)),
                ('libelle_ar', models.CharField(blank=True, max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nationalité',
                'verbose_name_plural': 'Nationalités',
                'db_table': 'nationalites',
                'ordering': ['libelle_fr'],
            },
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle_fr', models.CharField(max_length=200)),
                ('type_demande', models.CharField(blank=True, max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('devise', models.CharField(default='MRU', max_length=5)),
                ('date_effet', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tarifs',
                'db_table': 'tarifs',
                'ordering': ['libelle_fr'],
            },
        ),
        migrations.CreateModel(
            name='TypeDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle_fr', models.CharField(max_length=200)),
                ('libelle_ar', models.CharField(blank=True, max_length=200)),
                ('type_entite', models.CharField(choices=[('PH', 'PH'), ('PM', 'PM'), ('SC', 'SC'), ('ALL', 'Tous')], default='ALL', max_length=5)),
                ('delai_traitement', models.IntegerField(default=5)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type de demande',
                'verbose_name_plural': 'Types de demandes',
                'db_table': 'types_demandes',
                'ordering': ['libelle_fr'],
            },
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('libelle_fr', models.CharField(max_length=200)),
                ('libelle_ar', models.CharField(blank=True, max_length=200)),
                ('type_demande', models.CharField(blank=True, max_length=20)),
                ('obligatoire', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type de document',
                'verbose_name_plural': 'Types de documents',
                'db_table': 'types_documents',
                'ordering': ['libelle_fr'],
            },
        ),
        migrations.CreateModel(
            name='Localite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle_fr', models.CharField(max_length=150)),
                ('libelle_ar', models.CharField(blank=True, max_length=150)),
                ('type', models.CharField(choices=[('WILAYA', 'Wilaya'), ('MOUGHATAA', 'Moughataa'), ('COMMUNE', 'Commune')], default='WILAYA', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants', to='parametrage.localite')),
            ],
            options={
                'verbose_name': 'Localité',
                'verbose_name_plural': 'Localités',
                'db_table': 'localites',
                'ordering': ['libelle_fr'],
            },
        ),
    ]
