# Generated by Django 4.2.11 on 2026-04-22 01:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeRadiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('fondement', models.CharField(choices=[('consentement', 'Consentement à la radiation (acte authentique ou sous seing privé)'), ('jugement', 'Décision judiciaire (art. 92)'), ('requerant_original', "Radiation par la personne ayant procédé à l'inscription")], max_length=32, verbose_name='Fondement (art. 92)')),
                ('statut', models.CharField(choices=[('recue', 'Reçue'), ('rejetee', 'Rejetée'), ('appliquee', 'Appliquée')], default='recue', max_length=16, verbose_name='Statut')),
                ('motif_refus', models.CharField(blank=True, max_length=255, verbose_name='Motif de refus')),
                ('applique_le', models.DateTimeField(blank=True, null=True, verbose_name='Appliquée le')),
                ('nom_constituant', models.CharField(blank=True, max_length=150, verbose_name='Nom du constituant')),
                ('prenom_constituant', models.CharField(blank=True, max_length=150, verbose_name='Prénom du constituant')),
                ('denomination_constituant', models.CharField(blank=True, max_length=255, verbose_name='Dénomination sociale du constituant')),
                ('adresse_constituant', models.TextField(blank=True, verbose_name='Adresse du constituant')),
                ('numero_rc_constituant', models.CharField(blank=True, max_length=64, verbose_name='N° RC du constituant (si applicable)')),
            ],
            options={
                'verbose_name': 'Demande de radiation',
                'verbose_name_plural': 'Demandes de radiation',
                'ordering': ('-cree_le',),
            },
        ),
    ]
