# Generated by Django 4.2.11 on 2026-04-22 01:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibelleCanalSaisie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('libelle_fr', models.CharField(blank=True, max_length=255, verbose_name='Libellé français')),
                ('libelle_ar', models.CharField(blank=True, max_length=255, verbose_name='Libellé arabe')),
                ('langue_faisant_foi', models.CharField(choices=[('fr', 'Français'), ('ar', 'Arabe'), ('equ', 'Équivalent établi FR et AR')], default='equ', help_text='Langue de référence lorsque les deux versions ne sont pas strictement équivalentes (§ 7.4 des TDR).', max_length=3, verbose_name='Langue faisant foi')),
                ('cle', models.CharField(max_length=64, unique=True, verbose_name='Clé technique')),
                ('description_fr', models.TextField(blank=True, verbose_name='Description (FR)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (AR)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Libellé — canal de saisie',
                'verbose_name_plural': 'Libellés — canaux de saisie',
                'ordering': ('ordre', 'cle'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LibelleCritereRecherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('libelle_fr', models.CharField(blank=True, max_length=255, verbose_name='Libellé français')),
                ('libelle_ar', models.CharField(blank=True, max_length=255, verbose_name='Libellé arabe')),
                ('langue_faisant_foi', models.CharField(choices=[('fr', 'Français'), ('ar', 'Arabe'), ('equ', 'Équivalent établi FR et AR')], default='equ', help_text='Langue de référence lorsque les deux versions ne sont pas strictement équivalentes (§ 7.4 des TDR).', max_length=3, verbose_name='Langue faisant foi')),
                ('cle', models.CharField(max_length=64, unique=True, verbose_name='Clé technique')),
                ('description_fr', models.TextField(blank=True, verbose_name='Description (FR)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (AR)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Libellé — critère de recherche (art. 96)',
                'verbose_name_plural': 'Libellés — critères de recherche (art. 96)',
                'ordering': ('ordre', 'cle'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LibelleMotifRejet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('libelle_fr', models.CharField(blank=True, max_length=255, verbose_name='Libellé français')),
                ('libelle_ar', models.CharField(blank=True, max_length=255, verbose_name='Libellé arabe')),
                ('langue_faisant_foi', models.CharField(choices=[('fr', 'Français'), ('ar', 'Arabe'), ('equ', 'Équivalent établi FR et AR')], default='equ', help_text='Langue de référence lorsque les deux versions ne sont pas strictement équivalentes (§ 7.4 des TDR).', max_length=3, verbose_name='Langue faisant foi')),
                ('cle', models.CharField(max_length=64, unique=True, verbose_name='Clé technique')),
                ('description_fr', models.TextField(blank=True, verbose_name='Description (FR)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (AR)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Libellé — motif de rejet (art. 80)',
                'verbose_name_plural': 'Libellés — motifs de rejet (art. 80)',
                'ordering': ('ordre', 'cle'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LibelleNatureDroit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('libelle_fr', models.CharField(blank=True, max_length=255, verbose_name='Libellé français')),
                ('libelle_ar', models.CharField(blank=True, max_length=255, verbose_name='Libellé arabe')),
                ('langue_faisant_foi', models.CharField(choices=[('fr', 'Français'), ('ar', 'Arabe'), ('equ', 'Équivalent établi FR et AR')], default='equ', help_text='Langue de référence lorsque les deux versions ne sont pas strictement équivalentes (§ 7.4 des TDR).', max_length=3, verbose_name='Langue faisant foi')),
                ('cle', models.CharField(max_length=64, unique=True, verbose_name='Clé technique')),
                ('description_fr', models.TextField(blank=True, verbose_name='Description (FR)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (AR)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Libellé — nature de droit inscrit',
                'verbose_name_plural': 'Libellés — natures de droits inscrits',
                'ordering': ('ordre', 'cle'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LibelleTypeCertificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('libelle_fr', models.CharField(blank=True, max_length=255, verbose_name='Libellé français')),
                ('libelle_ar', models.CharField(blank=True, max_length=255, verbose_name='Libellé arabe')),
                ('langue_faisant_foi', models.CharField(choices=[('fr', 'Français'), ('ar', 'Arabe'), ('equ', 'Équivalent établi FR et AR')], default='equ', help_text='Langue de référence lorsque les deux versions ne sont pas strictement équivalentes (§ 7.4 des TDR).', max_length=3, verbose_name='Langue faisant foi')),
                ('cle', models.CharField(max_length=64, unique=True, verbose_name='Clé technique')),
                ('description_fr', models.TextField(blank=True, verbose_name='Description (FR)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (AR)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Libellé — type de certificat',
                'verbose_name_plural': 'Libellés — types de certificats',
                'ordering': ('ordre', 'cle'),
                'abstract': False,
            },
        ),
    ]
