# Generated by Django 4.2.9 on 2026-04-05 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registres', '0001_initial'),
        ('entites', '0001_initial'),
        ('demandes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_cession', models.CharField(max_length=30, unique=True)),
                ('date_cession', models.DateField(auto_now_add=True)),
                ('type_cession', models.CharField(blank=True, choices=[('FONDS_COMMERCE', 'Fonds de commerce'), ('PARTS_SOCIALES', 'Parts sociales'), ('ACTIONS', 'Actions')], max_length=20)),
                ('prix_cession', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée'), ('ANNULEE', 'Annulée')], db_index=True, default='EN_COURS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('cedant_ph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cessions_cedant_ph', to='entites.personnephysique')),
                ('cedant_pm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cessions_cedant_pm', to='entites.personnemorale')),
                ('cessionnaire_ph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cessions_cessionnaire_ph', to='entites.personnephysique')),
                ('cessionnaire_pm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cessions_cessionnaire_pm', to='entites.personnemorale')),
                ('chrono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registres.registrechronologique')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cessions_creees', to=settings.AUTH_USER_MODEL)),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demandes.demande')),
                ('ra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cessions', to='registres.registreanalytique')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cessions_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cession',
                'verbose_name_plural': 'Cessions',
                'db_table': 'cessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
