# Generated by Django 4.2.9 on 2026-04-06 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cessions', '0003_cession_cleanup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cession',
            name='demande',
        ),
    ]
