# Generated by Django 4.2.11 on 2026-04-22 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitionStatut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inscription', models.CharField(db_index=True, max_length=64, verbose_name="Numéro d'inscription concerné")),
                ('statut_avant', models.CharField(blank=True, choices=[('recue', 'Reçue'), ('en_controle_forme', 'En contrôle de forme'), ('rejetee', 'Rejetée'), ('inscrite', 'Inscrite (en cours de validité)'), ('modifiee', 'Modifiée'), ('renouvelee', 'Renouvelée'), ('radiee', 'Radiée (en cours de validité)'), ('expiree', 'Expirée'), ('archivee', 'Archivée (fichier général)')], help_text='Vide pour la première transition (création de la demande).', max_length=32, verbose_name='Statut avant')),
                ('statut_apres', models.CharField(choices=[('recue', 'Reçue'), ('en_controle_forme', 'En contrôle de forme'), ('rejetee', 'Rejetée'), ('inscrite', 'Inscrite (en cours de validité)'), ('modifiee', 'Modifiée'), ('renouvelee', 'Renouvelée'), ('radiee', 'Radiée (en cours de validité)'), ('expiree', 'Expirée'), ('archivee', 'Archivée (fichier général)')], max_length=32, verbose_name='Statut après')),
                ('evenement', models.CharField(max_length=64, verbose_name='Événement déclencheur')),
                ('articles_fondateurs', models.CharField(help_text='Ex. ``art. 85, 86``.', max_length=64, verbose_name='Articles fondateurs')),
                ('motif', models.CharField(blank=True, max_length=255, verbose_name='Motif / justification')),
                ('instant', models.DateTimeField(db_index=True, verbose_name='Instant')),
                ('acteur_role', models.CharField(blank=True, max_length=48, verbose_name='Rôle applicatif actif')),
                ('automatique', models.BooleanField(default=False, verbose_name='Transition automatique')),
                ('acteur', models.ForeignKey(blank=True, help_text='Nul pour les transitions automatiques (ex. expiration).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Acteur')),
            ],
            options={
                'verbose_name': 'Transition de statut',
                'verbose_name_plural': 'Historique des transitions',
                'ordering': ('-instant', '-id'),
                'indexes': [models.Index(fields=['numero_inscription', 'instant'], name='workflow_tr_numero__125dd3_idx')],
            },
        ),
    ]
