# Generated by Django 4.2.11 on 2026-04-22 01:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('type_partie', models.CharField(choices=[('pp', 'Personne physique'), ('pm', 'Personne morale')], max_length=2, verbose_name='Type de partie')),
                ('nom', models.CharField(blank=True, max_length=150, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=150, verbose_name='Prénom(s)')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=150, verbose_name='Lieu de naissance')),
                ('denomination_sociale', models.CharField(blank=True, max_length=255, verbose_name='Dénomination sociale')),
                ('numero_rc', models.CharField(blank=True, db_index=True, help_text="Article 96 — critère de recherche. Saisi tel que déclaré ; l'interconnexion avec le RCCM est GELÉE à ce stade.", max_length=64, verbose_name="Numéro d'immatriculation au RC")),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse du domicile')),
                ('adresse_electronique', models.EmailField(blank=True, help_text='Collectée sans obligation (art. 85 avant-dernier alinéa) ; utilisée uniquement pour notifications si fournie.', max_length=254, verbose_name='Adresse électronique (facultative, art. 85)')),
                ('telephone', models.CharField(blank=True, max_length=32, verbose_name='Téléphone')),
            ],
            options={
                'verbose_name': 'Partie',
                'verbose_name_plural': 'Parties',
            },
        ),
    ]
