# Generated by Django 4.2.11 on 2026-04-22 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partie',
            name='cree_par',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='partie',
            name='modifie_par',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AddIndex(
            model_name='partie',
            index=models.Index(fields=['nom', 'prenom'], name='parties_par_nom_ee1b59_idx'),
        ),
        migrations.AddIndex(
            model_name='partie',
            index=models.Index(fields=['denomination_sociale'], name='parties_par_denomin_ca7e06_idx'),
        ),
        migrations.AddIndex(
            model_name='partie',
            index=models.Index(fields=['numero_rc'], name='parties_par_numero__068248_idx'),
        ),
        migrations.AddConstraint(
            model_name='partie',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('denomination_sociale', ''), ('type_partie', 'pp')), ('type_partie', 'pm'), _connector='OR'), name='pp_sans_denomination'),
        ),
    ]
