# Generated by Django 4.2.11 on 2026-05-31 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partie',
            name='nni',
            field=models.CharField(blank=True, db_index=True, help_text="Numéro national d'identification (Mauritanie) ou autre identifiant fourni. Information déclarative, non vérifiée par le greffe (art. 86).", max_length=64, verbose_name='NNI / identifiant national'),
        ),
        migrations.AddField(
            model_name='partie',
            name='representant_legal',
            field=models.CharField(blank=True, help_text='Nom du représentant légal pour la personne morale. Information déclarative.', max_length=255, verbose_name='Représentant légal'),
        ),
        migrations.AddField(
            model_name='partie',
            name='siege_social',
            field=models.CharField(blank=True, max_length=255, verbose_name='Siège social'),
        ),
        migrations.AlterField(
            model_name='partie',
            name='numero_rc',
            field=models.CharField(blank=True, db_index=True, help_text="Article 96 — critère de recherche. Saisi tel que déclaré ; l'interconnexion avec le RCCM est GELÉE à ce stade. Peut également porter un numéro d'identification fiscale (NIF).", max_length=64, verbose_name="Numéro d'immatriculation au RC / NIF"),
        ),
    ]
