# Generated by Django 4.2.11 on 2026-05-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0003_refonte_art85'),
    ]

    operations = [
        migrations.AddField(
            model_name='partie',
            name='type_identifiant',
            field=models.CharField(blank=True, choices=[('nni', "NNI (numéro national d'identification)"), ('passeport', 'Numéro de passeport')], default='nni', help_text='Détermine la nature de la valeur stockée dans ``nni`` : NNI mauritanien (10 chiffres) ou numéro de passeport (chaîne libre ≥ 4 caractères).', max_length=16, verbose_name="Type d'identifiant (personne physique)"),
        ),
        migrations.AlterField(
            model_name='partie',
            name='nni',
            field=models.CharField(blank=True, db_index=True, help_text="Valeur de l'identifiant. NNI : exactement 10 chiffres, non répétitifs. Passeport : numéro tel qu'il figure sur le document. Information déclarative (art. 86).", max_length=64, verbose_name='NNI / Numéro de passeport'),
        ),
    ]
