# Generated by Django 4.2.9 on 2026-04-05 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametrage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonneMorale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('denomination', models.CharField(max_length=300, verbose_name='Dénomination')),
                ('denomination_ar', models.CharField(blank=True, max_length=300, verbose_name='Dénomination (arabe)')),
                ('sigle', models.CharField(blank=True, max_length=50)),
                ('capital_social', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('devise_capital', models.CharField(default='MRU', max_length=5)),
                ('duree_societe', models.IntegerField(blank=True, null=True, verbose_name='Durée (ans)')),
                ('date_constitution', models.DateField(blank=True, null=True)),
                ('date_ag', models.DateField(blank=True, null=True, verbose_name='Date AG')),
                ('siege_social', models.TextField(blank=True, verbose_name='Siège social')),
                ('siege_social_ar', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site_web', models.URLField(blank=True)),
                ('bp', models.CharField(blank=True, max_length=50, verbose_name='Boîte postale')),
                ('nb_associes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('forme_juridique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametrage.formejuridique')),
                ('localite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametrage.localite')),
            ],
            options={
                'verbose_name': 'Personne morale',
                'verbose_name_plural': 'Personnes morales',
                'db_table': 'personnes_morales',
                'ordering': ['denomination'],
            },
        ),
        migrations.CreateModel(
            name='Succursale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('denomination', models.CharField(max_length=300)),
                ('denomination_ar', models.CharField(blank=True, max_length=300)),
                ('pays_origine', models.CharField(blank=True, max_length=100)),
                ('capital_affecte', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('devise', models.CharField(default='MRU', max_length=5)),
                ('siege_social', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('localite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametrage.localite')),
                ('pm_mere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='succursales', to='entites.personnemorale')),
            ],
            options={
                'verbose_name': 'Succursale',
                'verbose_name_plural': 'Succursales',
                'db_table': 'succursales',
                'ordering': ['denomination'],
            },
        ),
        migrations.CreateModel(
            name='PersonnePhysique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nni', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='NNI')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=150, verbose_name='Prénom')),
                ('nom_ar', models.CharField(blank=True, max_length=150, verbose_name='Nom (arabe)')),
                ('prenom_ar', models.CharField(blank=True, max_length=150, verbose_name='Prénom (arabe)')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=200, verbose_name='Lieu de naissance')),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('adresse_ar', models.TextField(blank=True, verbose_name='Adresse (arabe)')),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profession', models.CharField(blank=True, max_length=150)),
                ('situation_matrimoniale', models.CharField(blank=True, choices=[('CELIBATAIRE', 'Célibataire'), ('MARIE', 'Marié(e)'), ('DIVORCE', 'Divorcé(e)'), ('VEUF', 'Veuf/Veuve')], max_length=20)),
                ('nom_pere', models.CharField(blank=True, max_length=150)),
                ('nom_mere', models.CharField(blank=True, max_length=150)),
                ('num_passeport', models.CharField(blank=True, max_length=50)),
                ('num_carte_identite', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('localite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametrage.localite')),
                ('nationalite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametrage.nationalite')),
            ],
            options={
                'verbose_name': 'Personne physique',
                'verbose_name_plural': 'Personnes physiques',
                'db_table': 'personnes_physiques',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
