# Generated by Django 4.2.9 on 2026-04-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnephysique',
            name='profession',
            field=models.TextField(blank=True),
        ),
    ]
