# Generated by Django 4.2.11 on 2026-04-22 01:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('reference_demande', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Identifiant opaque attribué à la réception, visible du déposant avant l'attribution du numéro d'ordre.", unique=True, verbose_name='Référence de la demande')),
                ('numero_ordre', models.CharField(blank=True, help_text='Attribué à la transition vers « Inscrite ». Format : ``NNNNNN-AAAAMMJJHHMMSS``. Une fois attribué, immuable.', max_length=64, null=True, unique=True, verbose_name="Numéro d'ordre (art. 78)")),
                ('canal_saisie', models.CharField(choices=[('guichet_papier', 'Bordereau papier au guichet (art. 78)'), ('portail_electronique', 'Voie électronique (art. 78)')], max_length=32, verbose_name='Canal de saisie (art. 78)')),
                ('instant_arrivee', models.DateTimeField(db_index=True, help_text="Date et heure d'arrivée au point d'entrée retenu ; elle détermine l'ordre d'arrivée. NE SE CONFOND PAS avec l'instant de saisie opposable (art. 78 al. 3).", verbose_name="Instant d'arrivée (art. 78 al. 2)")),
                ('instant_saisie_opposable', models.DateTimeField(blank=True, db_index=True, help_text="Prise d'effet juridique. ⚠️ ZONE GELÉE § 5.1 — l'horodatage opposable définitif dépend de la source de temps arbitrée.", null=True, verbose_name='Instant de saisie dans le fichier public (art. 78, 87)')),
                ('statut', models.CharField(choices=[('recue', 'Reçue'), ('en_controle_forme', 'En contrôle de forme'), ('rejetee', 'Rejetée'), ('inscrite', 'Inscrite (en cours de validité)'), ('modifiee', 'Modifiée'), ('renouvelee', 'Renouvelée'), ('radiee', 'Radiée (en cours de validité)'), ('expiree', 'Expirée'), ('archivee', 'Archivée (fichier général)')], db_index=True, default='recue', max_length=32, verbose_name='Statut')),
                ('mention_radiee', models.BooleanField(default=False, help_text="Article 92 alinéa 2 : après radiation, les informations sont conservées au fichier public jusqu'à la date d'expiration avec mention « radiée ».", verbose_name='Mention « radiée » au fichier public')),
                ('fichier_actuel', models.CharField(choices=[('public', 'Fichier accessible au public (art. 77)'), ('general', 'Fichier général (art. 77, 79)')], db_index=True, default='public', max_length=16, verbose_name='Fichier de rattachement (art. 77)')),
                ('nature_droit', models.CharField(choices=[('nant_outillage', "Nantissement de l'outillage, du matériel ou du matériel professionnel"), ('nant_droits_associes', "Nantissement des droits d'associés, parts sociales, valeurs mobilières et comptes de titres financiers"), ('nant_fonds_commerce', 'Nantissement du fonds de commerce'), ('priv_vendeur_fonds', 'Privilège du vendeur de fonds de commerce'), ('nant_stocks', 'Nantissement des stocks'), ('priv_tresor', 'Privilège du Trésor'), ('priv_fiscal', 'Privilège des services fiscaux'), ('priv_douanes', "Privilège de l'administration des douanes"), ('priv_prevoyance', 'Privilège des organismes de prévoyance sociale'), ('nant_creance', 'Nantissement de créance'), ('nant_compte_bancaire', 'Nantissement de compte bancaire'), ('nant_pi', 'Nantissement des droits de propriété intellectuelle')], max_length=48, verbose_name='Nature du droit / sûreté (art. 85)')),
                ('somme_garantie', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Somme garantie (art. 85)')),
                ('monnaie', models.CharField(blank=True, help_text="Code ISO 4217 (ex. ``MRU``). Le code choisi est documenté par le maître d'ouvrage.", max_length=8, verbose_name='Monnaie')),
                ('duree_en_jours', models.PositiveIntegerField(help_text="Durée de l'inscription exprimée en jours. Le texte ne fixe pas de borne (risque signalé TDR § 9.2) ; une limite paramétrable pourra être mise en œuvre après arbitrage du MO.", verbose_name="Durée de l'inscription en jours (art. 85)")),
                ('date_expiration', models.DateField(blank=True, help_text="Date calculée à partir de l'instant de saisie opposable et de la durée déclarée ; prorogée en cas de renouvellement (art. 91).", null=True, verbose_name="Date d'expiration")),
                ('adresse_electronique_notifications', models.EmailField(blank=True, help_text='Facultative (art. 85 avant-dernier alinéa).', max_length=254, verbose_name='Adresse électronique pour notifications')),
                ('motif_rejet', models.CharField(blank=True, choices=[('canal_non_autorise', 'Demande soumise par un canal non autorisé (art. 80)'), ('informations_illisibles', 'Informations illisibles (art. 80)'), ('informations_incomprehensibles', 'Informations incompréhensibles (art. 80)')], max_length=48, verbose_name='Motif de rejet (art. 80)')),
                ('commentaire_rejet_fr', models.TextField(blank=True, verbose_name='Commentaire de rejet (FR)')),
                ('commentaire_rejet_ar', models.TextField(blank=True, verbose_name='Commentaire de rejet (AR)')),
                ('instant_rejet', models.DateTimeField(blank=True, null=True, verbose_name='Instant du rejet')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('nom_original', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('fichier', models.FileField(upload_to='pieces_jointes/%Y/%m/', verbose_name='Contenu')),
                ('type_mime', models.CharField(blank=True, max_length=128, verbose_name='Type MIME')),
                ('taille_octets', models.PositiveBigIntegerField(verbose_name='Taille (octets)')),
                ('sceau_empreinte', models.CharField(blank=True, help_text="Empreinte SHA-256 du fichier à des fins d'intégrité. ⚠️ Le scellement opposable reste GELÉ (TDR § 5.1).", max_length=128, verbose_name='Empreinte de scellement')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
            },
        ),
        migrations.CreateModel(
            name='SequenceNumeroOrdre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prochaine_valeur', models.PositiveBigIntegerField(default=1, verbose_name='Prochaine valeur')),
            ],
            options={
                'verbose_name': "Séquence du numéro d'ordre (art. 78)",
                'verbose_name_plural': "Séquence du numéro d'ordre (art. 78)",
            },
        ),
        migrations.CreateModel(
            name='RoleInscriptionPartie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('constituant', 'Constituant (art. 85)'), ('creancier', 'Créancier garanti (art. 85)'), ('debiteur', 'Débiteur (art. 85)'), ('requerant', 'Requérant (art. 85)')], max_length=16, verbose_name='Rôle')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('actif', models.BooleanField(db_index=True, default=True, verbose_name='Actif')),
                ('date_fin_validite', models.DateTimeField(blank=True, null=True, verbose_name='Fin de validité')),
                ('raison_fin', models.CharField(blank=True, max_length=255, verbose_name='Raison de fin de validité')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles_parties', to='inscriptions.inscription', verbose_name='Inscription')),
            ],
            options={
                'verbose_name': "Rôle d'une partie dans une inscription",
                'verbose_name_plural': 'Rôles des parties',
                'ordering': ('role', 'ordre', 'id'),
            },
        ),
    ]
