# Generated by Django 4.2.11 on 2026-04-22 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscriptions', '0001_initial'),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleinscriptionpartie',
            name='partie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles_dans_inscriptions', to='parties.partie', verbose_name='Partie'),
        ),
    ]
