# Generated by Django 4.2.11 on 2026-04-22 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parties', '0001_initial'),
        ('inscriptions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecejointe',
            name='cree_par',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='piecejointe',
            name='inscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pieces_jointes', to='inscriptions.inscription', verbose_name='Inscription'),
        ),
        migrations.AddField(
            model_name='piecejointe',
            name='modifie_par',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='cree_par',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='modifie_par',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='requerant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions_deposees', to='parties.partie', verbose_name='Requérant (art. 85)'),
        ),
        migrations.AddIndex(
            model_name='roleinscriptionpartie',
            index=models.Index(fields=['inscription', 'role', 'actif'], name='inscription_inscrip_8e707a_idx'),
        ),
        migrations.AddConstraint(
            model_name='roleinscriptionpartie',
            constraint=models.UniqueConstraint(condition=models.Q(('actif', True)), fields=('inscription', 'partie', 'role'), name='unique_partie_role_actif_par_inscription'),
        ),
        migrations.AddIndex(
            model_name='inscription',
            index=models.Index(fields=['statut', 'fichier_actuel'], name='inscription_statut_6f4b33_idx'),
        ),
        migrations.AddIndex(
            model_name='inscription',
            index=models.Index(fields=['instant_saisie_opposable'], name='inscription_instant_a4bb33_idx'),
        ),
        migrations.AddIndex(
            model_name='inscription',
            index=models.Index(fields=['numero_ordre'], name='inscription_numero__604f08_idx'),
        ),
        migrations.AddIndex(
            model_name='inscription',
            index=models.Index(fields=['date_expiration'], name='inscription_date_ex_8f8a37_idx'),
        ),
    ]
