# Generated by Django 4.2.11 on 2026-05-31 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='date_convention',
            field=models.DateField(blank=True, null=True, verbose_name='Date de la convention'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='debiteur_est_constituant',
            field=models.BooleanField(default=False, help_text='Quand vrai, le système réplique les constituants comme débiteurs (cas fréquent : sûreté constituée pour garantir sa propre dette). Évite la double saisie côté frontend.', verbose_name='Le débiteur est le constituant'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='montant_en_lettres_ar',
            field=models.CharField(blank=True, help_text='Idem en langue arabe.', max_length=512, verbose_name='Montant en lettres (AR)'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='montant_en_lettres_fr',
            field=models.CharField(blank=True, help_text='Conversion en lettres du montant garanti, langue française. Calculée par le système ; conservée pour les certificats.', max_length=512, verbose_name='Montant en lettres (FR)'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='nature_convention',
            field=models.CharField(blank=True, choices=[('notariee', 'Convention notariée'), ('sous_seing_prive', 'Convention sous seing privé')], help_text="Notariée ou sous seing privé. Information déclarative (art. 86) ; le greffe ne vérifie pas l'acte sous-jacent (TDR § 3.2).", max_length=24, verbose_name='Nature de la convention'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='nature_droit',
            field=models.CharField(help_text='Référence à une clé de ``referentiels.LibelleNatureDroit`` active au moment du dépôt. Liste paramétrable par le greffier (non rétroactif : les inscriptions existantes restent valides même si une nature est ultérieurement désactivée).', max_length=48, verbose_name='Nature du droit / sûreté (art. 85)'),
        ),
    ]
