# Generated by Django 4.2.11 on 2026-05-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0004_refonte_art85'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleinscriptionpartie',
            name='role',
            field=models.CharField(choices=[('constituant', 'Constituant (art. 85)'), ('creancier', 'Créancier garanti (art. 85)'), ('debiteur', 'Débiteur (art. 85)'), ('requerant', 'Requérant (art. 85)'), ('agent_surete', 'Agent de sûreté (mandataire des créanciers, facultatif — décision MO)')], max_length=16, verbose_name='Rôle'),
        ),
    ]
