# Generated by Django 4.2.11 on 2026-05-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0005_agent_surete'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='donnees_specifiques',
            field=models.JSONField(blank=True, default=dict, help_text='Dictionnaire des champs spécifiques au type_surete déposé (ex. date du contrat de vente, prix total, durée, etc.). Forme libre côté backend (régime déclaratif art. 86) ; validé en amont par les formulaires.', verbose_name='Données spécifiques au type de sûreté'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='type_surete',
            field=models.CharField(choices=[('depot_surete', 'Déposer une sûreté (générique)'), ('privilege_vendeur', 'Privilège du vendeur'), ('reserve_propriete', 'Vente avec réserve du droit de propriété'), ('credit_bail', 'Contrat de crédit-bail')], db_index=True, default='depot_surete', help_text='Distinction métier entre les 4 parcours de dépôt : sûreté générique (art. 76), privilège du vendeur, vente avec réserve de propriété, crédit-bail. Les éventuelles données spécifiques au type sont conservées dans ``donnees_specifiques``.', max_length=32, verbose_name="Type de sûreté objet de l'inscription"),
        ),
    ]
