# Generated by Django 4.2.11 on 2026-05-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0006_type_surete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon (non encore soumis au greffe)'), ('recue', 'Reçue / Soumise au greffe'), ('en_controle_forme', 'En contrôle de forme — en attente de validation'), ('retournee', 'Retournée au déclarant pour correction (workflow Greffier ⇄ Déclarant)'), ('rejetee', 'Rejetée'), ('inscrite', 'Inscrite (en cours de validité)'), ('modifiee', 'Modifiée'), ('renouvelee', 'Renouvelée'), ('radiee', 'Radiée (en cours de validité)'), ('expiree', 'Expirée'), ('archivee', 'Archivée (fichier général)')], db_index=True, default='recue', max_length=32, verbose_name='Statut'),
        ),
    ]
