# Generated by Django 4.2.11 on 2026-05-31 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inscriptions', '0007_workflow_demande_inscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationRetour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('observation_fr', models.TextField(help_text='Observation détaillée motivant le retour. Obligatoire et non vide. Visible du déclarant.', verbose_name='Observation du greffier (FR)')),
                ('observation_ar', models.TextField(help_text='Observation détaillée motivant le retour, version arabe. Obligatoire et non vide. Parité juridique avec FR.', verbose_name='Observation du greffier (AR)')),
                ('statut_au_moment', models.CharField(max_length=32, verbose_name="Statut de l'inscription au moment du retour")),
                ('instant_resoumission', models.DateTimeField(blank=True, help_text='Renseigné une seule fois lorsque le déclarant resoumet la demande après correction. Immuable ensuite.', null=True, verbose_name='Instant de la resoumission par le déclarant')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retours_emis', to=settings.AUTH_USER_MODEL, verbose_name='Greffier ayant retourné la demande')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations_retour', to='inscriptions.inscription', verbose_name='Inscription concernée')),
                ('resoumis_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resoumissions_effectuees', to=settings.AUTH_USER_MODEL, verbose_name='Déclarant ayant resoumis la demande')),
            ],
            options={
                'verbose_name': 'Observation de retour',
                'verbose_name_plural': 'Observations de retour',
                'ordering': ('cree_le',),
                'indexes': [models.Index(fields=['inscription', 'cree_le'], name='inscription_inscrip_a2904f_idx')],
            },
        ),
    ]
