# Generated by Django 4.2.11 on 2026-04-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequeteRecherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instant', models.DateTimeField(db_index=True, verbose_name='Instant de la recherche')),
                ('criteres_soumis', models.JSONField(default=dict, verbose_name='Critères soumis')),
                ('nombre_resultats', models.PositiveIntegerField(default=0, verbose_name='Nombre de résultats')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User-Agent')),
            ],
            options={
                'verbose_name': 'Requête de recherche',
                'verbose_name_plural': 'Requêtes de recherche',
                'ordering': ('-instant',),
            },
        ),
    ]
