# Generated by Django 4.2.11 on 2026-04-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntreeAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instant', models.DateTimeField(db_index=True, verbose_name='Instant')),
                ('categorie', models.CharField(choices=[('connexion', 'Connexion / déconnexion / tentative'), ('compte', 'Création ou modification de compte / rôle'), ('demande', "Dépôt d'une demande (inscription, modification, etc.)"), ('controle_forme', 'Contrôle de forme (art. 80)'), ('validation', "Validation par l'autorité de validation"), ('rejet', 'Rejet motivé (art. 80)'), ('certificat', "Délivrance d'un certificat"), ('recherche', "Lancement d'une recherche publique"), ('export_stat', 'Export statistique (art. 82)'), ('admin', "Opération d'administration"), ('systeme', 'Événement système')], db_index=True, max_length=32, verbose_name='Catégorie')),
                ('action_cle', models.CharField(help_text="Identifiant stable de l'action, indépendant de la langue (ex. ``inscription.creer``, ``recherche.lancer``, ``rejet.prononcer``).", max_length=80, verbose_name='Action (clé métier)')),
                ('acteur_role', models.CharField(blank=True, help_text="Rôle sous lequel l'action a été exécutée (§ 4.1 du TDR).", max_length=48, verbose_name='Rôle applicatif')),
                ('objet_type', models.CharField(blank=True, help_text='ex. ``inscription``, ``modification``, ``utilisateur``.', max_length=64, verbose_name="Type d'objet")),
                ('objet_reference', models.CharField(blank=True, help_text="Référence stable (numéro d'inscription, identifiant de demande, identifiant utilisateur, etc.).", max_length=120, verbose_name="Référence de l'objet")),
                ('resultat', models.CharField(choices=[('succes', 'Succès'), ('echec', 'Échec'), ('rejet', 'Rejet pour motif limitatif (art. 80)'), ('refus_autorisation', "Refus d'autorisation")], max_length=32, verbose_name='Résultat')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Données complémentaires structurées (diff avant/après, motifs, critères de recherche, etc.). Aucun champ libre en langue locale pour préserver la neutralité linguistique § 7.6.', verbose_name='Détails')),
                ('empreinte_precedente', models.CharField(blank=True, max_length=128, verbose_name='Empreinte précédente')),
                ('empreinte', models.CharField(db_index=True, max_length=128, verbose_name="Empreinte de l'entrée")),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User-Agent')),
            ],
            options={
                'verbose_name': "Entrée du journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ('-instant', '-id'),
            },
        ),
    ]
