# Generated by Django 4.2.11 on 2026-04-22 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entreeaudit',
            name='acteur',
            field=models.ForeignKey(blank=True, help_text='Nul uniquement pour les événements système non imputables.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entrees_audit', to=settings.AUTH_USER_MODEL, verbose_name='Acteur'),
        ),
        migrations.AddIndex(
            model_name='entreeaudit',
            index=models.Index(fields=['categorie', 'instant'], name='audit_entre_categor_e21150_idx'),
        ),
        migrations.AddIndex(
            model_name='entreeaudit',
            index=models.Index(fields=['objet_type', 'objet_reference'], name='audit_entre_objet_t_48a15f_idx'),
        ),
    ]
