# Generated by Django 4.2.11 on 2026-05-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_append_only_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreeaudit',
            name='categorie',
            field=models.CharField(choices=[('connexion', 'Connexion / déconnexion / tentative'), ('compte', 'Création ou modification de compte / rôle'), ('demande', "Dépôt d'une demande (inscription, modification, etc.)"), ('controle_forme', 'Contrôle de forme (art. 80)'), ('validation', "Validation par l'autorité de validation"), ('rejet', 'Rejet motivé (art. 80)'), ('retour_correction', 'Retour au déclarant pour correction (workflow MO 2026-05-31)'), ('certificat', "Délivrance d'un certificat"), ('recherche', "Lancement d'une recherche publique"), ('export_stat', 'Export statistique (art. 82)'), ('admin', "Opération d'administration"), ('systeme', 'Événement système')], db_index=True, max_length=32, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='entreeaudit',
            name='resultat',
            field=models.CharField(choices=[('succes', 'Succès'), ('echec', 'Échec'), ('rejet', 'Rejet pour motif limitatif (art. 80)'), ('refus_autorisation', "Refus d'autorisation"), ('retour_pour_correction', 'Retour au déclarant pour correction (réversible)')], max_length=32, verbose_name='Résultat'),
        ),
    ]
