# Generated by Django 4.2.11 on 2026-04-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionStatistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instant', models.DateTimeField(auto_now_add=True, verbose_name="Instant de l'extraction")),
                ('perimetre', models.JSONField(default=dict, help_text="Critères d'agrégation (période, nature de droit, canal, etc.).", verbose_name='Périmètre demandé')),
                ('resultat', models.JSONField(default=dict, verbose_name='Résultat')),
            ],
            options={
                'verbose_name': 'Extraction statistique (art. 82)',
                'verbose_name_plural': 'Extractions statistiques (art. 82)',
                'ordering': ('-instant',),
            },
        ),
    ]
