# Generated by Django 4.2.11 on 2026-04-22 01:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cree_le', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('description_fr', models.TextField(blank=True, verbose_name='Description (français)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (arabe)')),
                ('langue_faisant_foi_description', models.CharField(choices=[('fr', 'Français'), ('ar', 'Arabe'), ('equ', 'Équivalent établi FR et AR')], default='equ', max_length=3, verbose_name='Langue faisant foi (description)')),
                ('objet_modification_fr', models.TextField(verbose_name='Objet de la modification (FR)')),
                ('objet_modification_ar', models.TextField(verbose_name='Objet de la modification (AR)')),
                ('diff_propose', models.JSONField(default=dict, verbose_name='Différentiel proposé')),
                ('statut', models.CharField(choices=[('recue', 'Reçue'), ('rejetee', 'Rejetée (art. 80 ou effet utile art. 88)'), ('appliquee', 'Appliquée')], default='recue', max_length=16, verbose_name='Statut')),
                ('motif_refus_code', models.CharField(blank=True, choices=[('etat_final_constituant_absent', 'État final sans constituant actif (art. 88 dernier al.)'), ('etat_final_creancier_absent', 'État final sans créancier garanti actif (art. 88 dernier al.)'), ('etat_final_bien_absent', 'État final sans bien grevé actif (art. 88 dernier al.)'), ('accords_manquants', 'Accords du créancier et/ou du constituant non confirmés (art. 88)'), ('statut_inscription_incompatible', 'Inscription non en cours de validité (§ 4.3 TDR)'), ('diff_invalide', 'Diff non conforme au schéma strict (art. 78 / 88 / 90 al. 2)'), ('diff_vide', 'Aucune modification effective proposée'), ('demande_non_applicable', 'Demande déjà traitée (appliquée ou rejetée)')], max_length=48, verbose_name='Motif de refus (clé limitative)')),
                ('motif_refus', models.CharField(blank=True, help_text='Précision humaine, facultative. La référence juridique opposable est portée par ``motif_refus_code``.', max_length=255, verbose_name='Motif de refus — détail')),
                ('applique_le', models.DateTimeField(blank=True, null=True, verbose_name='Appliquée le')),
                ('accord_createur_confirme', models.BooleanField(default=False, help_text='Signature électronique GELÉE (§ 5.1, art. 88).', verbose_name='Accord du créancier confirmé')),
                ('accord_constituant_confirme', models.BooleanField(default=False, verbose_name='Accord du constituant confirmé')),
            ],
            options={
                'verbose_name': 'Demande de modification',
                'verbose_name_plural': 'Demandes de modification',
                'ordering': ('-cree_le',),
            },
        ),
        migrations.CreateModel(
            name='SnapshotInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evenement', models.CharField(choices=[('demande_recue', 'Demande reçue (avant application)'), ('validation_inscription', "Après validation de l'inscription"), ('modification_avant', 'Avant modification (art. 88)'), ('modification_apres', 'Après modification (art. 88)'), ('renouvellement_avant', 'Avant renouvellement (art. 91)'), ('renouvellement_apres', 'Après renouvellement (art. 91)'), ('radiation_avant', 'Avant radiation (art. 92)'), ('radiation_apres', 'Après radiation (art. 92)')], db_index=True, max_length=48, verbose_name='Événement déclencheur')),
                ('instant', models.DateTimeField(db_index=True, verbose_name='Instant')),
                ('contenu', models.JSONField(verbose_name='Contenu canonique')),
                ('empreinte', models.CharField(help_text='SHA-256 du contenu canonique. Mode STUB — § 5.1 TDR.', max_length=128, verbose_name='Empreinte de scellement')),
            ],
            options={
                'verbose_name': "Snapshot d'inscription",
                'verbose_name_plural': "Snapshots d'inscription",
                'ordering': ('inscription_id', 'instant', 'id'),
            },
        ),
    ]
