# Generated by Django 4.2.11 on 2026-04-22 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inscriptions', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshotinscription',
            name='acteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Acteur'),
        ),
        migrations.AddField(
            model_name='snapshotinscription',
            name='demande_modification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='modifications.demandemodification', verbose_name='Demande de modification rattachée'),
        ),
        migrations.AddField(
            model_name='snapshotinscription',
            name='inscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='inscriptions.inscription', verbose_name='Inscription'),
        ),
        migrations.AddField(
            model_name='demandemodification',
            name='cree_par',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='demandemodification',
            name='inscription',
            field=models.ForeignKey(help_text="Article 93 — la modification est rattachée au numéro de l'inscription initiale.", on_delete=django.db.models.deletion.PROTECT, related_name='demandes_modification', to='inscriptions.inscription', verbose_name='Inscription initiale'),
        ),
        migrations.AddField(
            model_name='demandemodification',
            name='modifie_par',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AddIndex(
            model_name='snapshotinscription',
            index=models.Index(fields=['inscription', 'evenement'], name='modificatio_inscrip_cf3514_idx'),
        ),
    ]
