# Generated by Django 4.2.9 on 2026-04-05 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandes', '0001_initial'),
        ('registres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Radiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_radia', models.CharField(max_length=30, unique=True)),
                ('date_radiation', models.DateField(auto_now_add=True)),
                ('motif', models.CharField(blank=True, choices=[('CESSATION', "Cessation d'activité"), ('DISSOLUTION', 'Dissolution'), ('LIQUIDATION', 'Liquidation'), ('FUSION', 'Fusion'), ('FAILLITE', 'Faillite'), ('AUTRE', 'Autre')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée'), ('ANNULEE', 'Annulée')], db_index=True, default='EN_COURS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('chrono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registres.registrechronologique')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiations_creees', to=settings.AUTH_USER_MODEL)),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demandes.demande')),
                ('ra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='radiations', to='registres.registreanalytique')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiations_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Radiation',
                'verbose_name_plural': 'Radiations',
                'db_table': 'radiations',
                'ordering': ['-created_at'],
            },
        ),
    ]
